import { Router } from "express";
import multer from "multer";
import { transcribeAudio } from "../services/whisper.js";
import { saveScript } from "../services/scriptSave.js";
import { splitAudioIntoChunks } from "../services/audioChunk.js";
import { prisma } from "@carpoolink/database";

const router = Router();
const upload = multer({ storage: multer.memoryStorage() }); // 파일을 메모리에 임시 저장
const MEDIA_SERVER_URL = process.env.MEDIA_SERVER_URL || 'http://localhost:4002';

const COMMANDS = [
  { keywords: ['질문', '다시'], type: 'READ_QUESTION_AGAIN' },  // 질문 다시 듣기
  { keywords: ['질문', '듣기'], type: 'READ_QUESTION' },        // 질문 듣기
  { keywords: ['답변', '완료'], type: 'COMPLETE_ANSWER' },      // 질문 답변 완료
];

const privateState = new Map();

/*
POST /stt/chunk
multipart/form-data:
    - audio: 오디오 파일 (wav, mp3 등)
    - userId: string
    - mentoringId: string
    - chunkIndex: string (숫자)
    - startTime?: string (초 단위, 선택)
    - endTime?: string (초 단위, 선택)
*/
router.post("/chunk", upload.single("audio"), async (req, res) => {
  try {
    const { userId, mentoringId, chunkIndex, startTime, endTime, sessionOffset } = req.body;
    console.log('[STT] /chunk 수신', { userId, mentoringId, chunkIndex, audioSize: req.file?.size });

    // 필수값 체크
    if (!req.file || !userId || !mentoringId || chunkIndex === undefined) {
      return res.status(400).json({ error: "audio, userId, mentoringId, chunkIndex는 필수입니다." });
    }

    // multer 메모리 버퍼 → Whisper가 읽을 수 있는 File 객체로 변환
    const audioFile = new File(
      [req.file.buffer],
      req.file.originalname || `chunk_${chunkIndex}.wav`,
      { type: req.file.mimetype }
    );

    // 1. Whisper STT
    const text = await transcribeAudio(audioFile);

    // 너무 짧거나 명백한 할루시네이션 필터링
    if (!text || text.trim().length < 2) {
      return res.json({ text: '', chunkIndex: parseInt(chunkIndex) });
    }

    const commandType = detectCommand(text);
    if (commandType) {
      console.log(`[COMMAND] ${commandType} - "${text}"`);
      fetch(`${MEDIA_SERVER_URL}/commands/execute`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ type: commandType, mentoringId, userId }),
      }).catch((e) => console.error('[COMMAND] 전송 실패', e.message));
    }

    const isPrivate = privateState.get(String(mentoringId)) ?? false;

    // 2. DB 저장
    const saved = await saveScript(
      {
        text,
        chunkIndex: parseInt(chunkIndex),
        startTime: startTime ? parseFloat(startTime) : undefined,
        endTime: endTime ? parseFloat(endTime) : undefined,
        sessionOffset: sessionOffset ? parseFloat(sessionOffset) : undefined,
        isPrivate,
      },
      {
        userId,
        mentoringId,
      }
    );

    res.json({
      scriptId: saved.scriptId.toString(),
      text,
      chunkIndex: parseInt(chunkIndex),
      ...(commandType && { command: commandType }),
    });
  } catch (err) {
    console.error("[STT ERROR]", err);
    res.status(500).json({ error: err.message });
  }
});

/*
POST /stt/text
TTS로 읽은 질문 등을 STT 스크립트 DB에 직접 텍스트로 저장하는 엔드포인트
*/
router.post("/text", async (req, res) => {
  try {
    const { userId, mentoringId, text, isPrivate } = req.body;

    if (!userId || !mentoringId || !text) {
      return res.status(400).json({ success: false, error: "필수 파라미터 누락" });
    }

    // 마이크 음성이 아니므로 chunkIndex를 -1 또는 임의의 값으로 주어 DB에 저장
    const savedScript = await prisma.script.create({
      data: {
        userId: BigInt(userId),
        mentoringId: BigInt(mentoringId),
        content: { text: text, chunkIndex: -1, isAutoGenerated: true },
        isPrivate: isPrivate || false,
      }
    });

    return res.json({
      success: true,
      script: {
        scriptId: savedScript.scriptId.toString(),
        text: text
      }
    });
  } catch (err) {
    console.error("🚨 텍스트 스크립트 저장 에러:", err);
    return res.status(500).json({ success: false, error: err.message });
  }
});

//긴 오디오 파일 업로드 → 청크 분할 → STT → DB 저장
router.post("/upload", upload.single("audio"), async (req, res) => {
  try {
    const { userId, mentoringId } = req.body;

    if (!req.file || !userId || !mentoringId) {
      return res.status(400).json({ error: "audio, userId, mentoringId는 필수입니다." });
    }

    // 멘토링 정보 조회
    const mentoring = await prisma.mentoring.findUnique({
      where: { mentoringId: BigInt(mentoringId) },
    });

    if (!mentoring) {
      return res.status(404).json({ error: "멘토링을 찾을 수 없습니다." });
    }

    // 발화자 userId 결정(1:N인 경우 멘토로 고정)
    const speakerUserId = mentoring.isGroup ? mentoring.userId.toString() : userId;

    // 비공개 질문에 대한 답변 시 isPrivate 설정
    const isPrivate = privateState.get(String(mentoringId)) ?? false;

    // 1. 청크 분할
    const chunks = await splitAudioIntoChunks(req.file.buffer, req.file.mimetype);

    // 2. 각 청크 STT + DB 저장
    const results = [];
    for (const chunk of chunks) {
      const audioFile = new File(
        [chunk.buffer],
        `chunk_${chunk.index}.wav`,
        { type: req.file.mimetype }
      );

      const text = await transcribeAudio(audioFile);

      const saved = await saveScript(
        {
          text,
          chunkIndex: chunk.index,
          startTime: chunk.startTime,
          endTime: chunk.endTime,
          isPrivate,
        },
        { userId: speakerUserId, mentoringId }
      );

      results.push({
        scriptId: saved.scriptId.toString(),
        chunkIndex: chunk.index,
        startTime: chunk.startTime,
        endTime: chunk.endTime,
        speakerUserId,
        text,
      });
    }

    res.json({
      mentoringId,
      isGroup: mentoring.isGroup,
      speakerUserId,
      totalChunks: chunks.length,
      scripts: results
    });
  } catch (err) {
    console.error("[STT UPLOAD ERROR]", err);
    res.status(500).json({ error: err.message });
  }
});

// stt-service/routes/stt.js 내부의 GET 엔드포인트 수정
router.get("/mentoring/:mentoringId", async (req, res) => {
  try {
    const { mentoringId } = req.params;
    console.log(`[🔍 STT 조회 최종 가동] mentoringId: ${mentoringId}`);

    // 1. 멘토링 정보 기본 조회
    const mentoring = await prisma.mentoring.findUnique({
      where: { mentoringId: BigInt(mentoringId) },
    });

    // 2. Script를 가져올 때 해당 스크립트를 말한 User 테이블 정보(nickname, role)를 직접 관계 조인(include)합니다.
    const scripts = await prisma.script.findMany({
      where: { mentoringId: BigInt(mentoringId) },
      include: {
        user: true // 데이터베이스 상의 실제 유저 정보를 그대로 가져옵니다.
      },
      orderBy: { scriptId: "asc" }
    });

    console.log(`[📊 DB 조회 성공] 실제 데이터 ${scripts.length}개를 정규화 변환합니다.`);

    // 3. 프론트엔드 page.tsx 완벽 호환 구조 변환
    const serializedScripts = scripts.map(s => {
      let textVal = "";
      let startTimeVal = null;

      // content 내장 JSON 오브젝트 안전 파싱
      if (s.content && typeof s.content === 'object') {
        textVal = s.content.text || "";
        startTimeVal = s.content.startTime ?? s.content.timestamp ?? null;
      } else if (typeof s.content === 'string') {
        try {
          const parsed = JSON.parse(s.content);
          textVal = parsed.text || "";
          startTimeVal = parsed.startTime ?? null;
        } catch (e) {
          textVal = s.content;
        }
      }

      // DB에 실존하는 유저의 실제 nickname과 role을 추출하고, 없을 경우에만 예외 기본값을 부여합니다.
      const realNickname = s.user?.nickname || "알 수 없음";
      const realRole = s.user?.role || "MENTEE";

      return {
        scriptId: s.scriptId.toString(),
        userId: s.userId.toString(),
        mentoringId: s.mentoringId.toString(),
        isPrivate: s.isPrivate || false,
        isMasked: s.isMasked || false,
        content: {
          text: textVal,
          startTime: startTimeVal,
          chunkIndex: s.content?.chunkIndex || 0
        },
        // core-api 규격과 100% 일치하도록 user 객체 포맷 매핑
        user: {
          nickname: realNickname,
          role: realRole // 이제 "MENTOR"가 정상적으로 전달됩니다.
        }
      };
    });

    return res.json({
      success: true,
      mentoring: {
        mentoringId: mentoring ? mentoring.mentoringId.toString() : mentoringId,
        title: mentoring?.title || "라이브 멘토링 스크립트",
        startedAt: mentoring?.startedAt || new Date().toISOString(),
        isGroup: mentoring?.isGroup ?? false
      },
      scripts: serializedScripts
    });

  } catch (err) {
    console.error("🚨 [STT 서비스 최종 핸들러 크래시]:", err);
    return res.status(500).json({
      success: false,
      error: err.message
    });
  }
});

function detectCommand(text) {
  for (const cmd of COMMANDS) {
    if (cmd.keywords.every(k => text.includes(k)))
      return cmd.type;
  }
  return null;
}

// 비공개 상태 변경용 엔드포인트
router.post('/session/:mentoringId/private', (req, res) => {
  const { isPrivate } = req.body;
  privateState.set(String(req.params.mentoringId), Boolean(isPrivate));
  res.json({ ok: true });
})

// 멘토링 종료 시 stt 세션 상태를 정리하는 api
router.post('/session/:mentoringId/end', (req, res) => {
  privateState.delete(String(req.params.mentoringId));
  console.log('[STT] 세션 정리됨:', req.params.mentoringId, '| 남은 세션:', privateState.size);
  res.json({ ok: true });
})

export default router;